// This file is auto-generated by @hey-api/openapi-ts

export const PageSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        title: {
            type: 'string',
            maxLength: 255
        },
        subtitle: {
            type: 'string',
            maxLength: 255
        },
        slug: {
            type: 'string',
            maxLength: 255,
            pattern: '^[-a-zA-Z0-9_]+$'
        },
        data: {},
        status: {
            '$ref': '#/components/schemas/StatusEnum'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: ['created_at', 'id', 'title', 'updated_at']
} as const;

export const PatchedPageSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        title: {
            type: 'string',
            maxLength: 255
        },
        subtitle: {
            type: 'string',
            maxLength: 255
        },
        slug: {
            type: 'string',
            maxLength: 255,
            pattern: '^[-a-zA-Z0-9_]+$'
        },
        data: {},
        status: {
            '$ref': '#/components/schemas/StatusEnum'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    }
} as const;

export const PatchedPostSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        title: {
            type: 'string',
            maxLength: 255
        },
        subtitle: {
            type: 'string',
            maxLength: 255
        },
        slug: {
            type: 'string',
            maxLength: 255,
            pattern: '^[-a-zA-Z0-9_]+$'
        },
        featured_image_url: {
            type: 'string',
            maxLength: 2000
        },
        featured_image_caption: {
            type: 'string',
            maxLength: 255
        },
        featured: {
            type: 'boolean'
        },
        content: {
            type: 'string'
        },
        author: {
            type: 'string',
            maxLength: 255
        },
        status: {
            '$ref': '#/components/schemas/StatusEnum'
        },
        published_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    }
} as const;

export const PostSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        title: {
            type: 'string',
            maxLength: 255
        },
        subtitle: {
            type: 'string',
            maxLength: 255
        },
        slug: {
            type: 'string',
            maxLength: 255,
            pattern: '^[-a-zA-Z0-9_]+$'
        },
        featured_image_url: {
            type: 'string',
            maxLength: 2000
        },
        featured_image_caption: {
            type: 'string',
            maxLength: 255
        },
        featured: {
            type: 'boolean'
        },
        content: {
            type: 'string'
        },
        author: {
            type: 'string',
            maxLength: 255
        },
        status: {
            '$ref': '#/components/schemas/StatusEnum'
        },
        published_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: ['created_at', 'id', 'title', 'updated_at']
} as const;

export const StatusEnumSchema = {
    enum: ['draft', 'published'],
    type: 'string',
    description: `* \`draft\` - Draft
* \`published\` - Published`
} as const;