// This file is auto-generated by @hey-api/openapi-ts

export const PageSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        title: {
            type: 'string',
            maxLength: 255
        },
        pageName: {
            type: 'string',
            maxLength: 255
        },
        description: {
            type: 'string',
            maxLength: 255
        },
        slug: {
            type: 'string',
            maxLength: 255,
            pattern: '^[-a-zA-Z0-9_]+$'
        },
        repoUrl: {
            type: 'string',
            format: 'uri',
            maxLength: 2000
        },
        homepage: {
            type: 'string',
            maxLength: 2000
        },
        imageSrc: {
            type: 'string',
            maxLength: 2000
        },
        ordering: {
            type: 'integer',
            maximum: 2147483647,
            minimum: -2147483648
        },
        className: {
            type: 'string',
            maxLength: 255
        },
        published: {
            type: 'boolean'
        },
        imgClassName: {
            type: 'string',
            maxLength: 255
        },
        techStack: {
            type: 'array',
            items: {
                type: 'string',
                maxLength: 255
            },
            description: 'List of technologies used'
        },
        data: {},
        tags: {
            type: 'array',
            items: {
                type: 'string',
                maxLength: 128
            },
            description: 'List of tags for this page'
        },
        status: {
            '$ref': '#/components/schemas/StatusEnum'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: ['created_at', 'id', 'title', 'updated_at']
} as const;

export const PatchedPageSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        title: {
            type: 'string',
            maxLength: 255
        },
        pageName: {
            type: 'string',
            maxLength: 255
        },
        description: {
            type: 'string',
            maxLength: 255
        },
        slug: {
            type: 'string',
            maxLength: 255,
            pattern: '^[-a-zA-Z0-9_]+$'
        },
        repoUrl: {
            type: 'string',
            format: 'uri',
            maxLength: 2000
        },
        homepage: {
            type: 'string',
            maxLength: 2000
        },
        imageSrc: {
            type: 'string',
            maxLength: 2000
        },
        ordering: {
            type: 'integer',
            maximum: 2147483647,
            minimum: -2147483648
        },
        className: {
            type: 'string',
            maxLength: 255
        },
        published: {
            type: 'boolean'
        },
        imgClassName: {
            type: 'string',
            maxLength: 255
        },
        techStack: {
            type: 'array',
            items: {
                type: 'string',
                maxLength: 255
            },
            description: 'List of technologies used'
        },
        data: {},
        tags: {
            type: 'array',
            items: {
                type: 'string',
                maxLength: 128
            },
            description: 'List of tags for this page'
        },
        status: {
            '$ref': '#/components/schemas/StatusEnum'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    }
} as const;

export const PatchedPostSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        title: {
            type: 'string',
            maxLength: 255
        },
        subtitle: {
            type: 'string',
            maxLength: 255
        },
        slug: {
            type: 'string',
            maxLength: 255,
            pattern: '^[-a-zA-Z0-9_]+$'
        },
        featured_image_url: {
            type: 'string',
            maxLength: 2000
        },
        featured_image_caption: {
            type: 'string',
            maxLength: 255
        },
        featured: {
            type: 'boolean'
        },
        content: {
            type: 'string'
        },
        author: {
            type: 'string',
            maxLength: 255
        },
        status: {
            '$ref': '#/components/schemas/StatusEnum'
        },
        published_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        tags: {
            type: 'array',
            items: {
                type: 'string',
                maxLength: 128
            },
            description: 'List of tags for this post'
        }
    }
} as const;

export const PostSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        title: {
            type: 'string',
            maxLength: 255
        },
        subtitle: {
            type: 'string',
            maxLength: 255
        },
        slug: {
            type: 'string',
            maxLength: 255,
            pattern: '^[-a-zA-Z0-9_]+$'
        },
        featured_image_url: {
            type: 'string',
            maxLength: 2000
        },
        featured_image_caption: {
            type: 'string',
            maxLength: 255
        },
        featured: {
            type: 'boolean'
        },
        content: {
            type: 'string'
        },
        author: {
            type: 'string',
            maxLength: 255
        },
        status: {
            '$ref': '#/components/schemas/StatusEnum'
        },
        published_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        tags: {
            type: 'array',
            items: {
                type: 'string',
                maxLength: 128
            },
            description: 'List of tags for this post'
        }
    },
    required: ['created_at', 'id', 'title', 'updated_at']
} as const;

export const StatusEnumSchema = {
    enum: ['draft', 'published'],
    type: 'string',
    description: `* \`draft\` - Draft
* \`published\` - Published`
} as const;